---

certbot_force_create: false

# Read the doc (man certbot)
# --renew-by-default
# --keep-until-expiring
# --renew-with-new-domains
letsencrypt_renewal_behaviour: '--keep-until-expiring'

# set to true while debugging hook_template, because
# letsencrypt has a rate limite of 50 renewals per week.
letsencrypt_test: false
# set the certificate CN
letsencrypt_root_cn: ''
# hook template path and hook name
letsencrypt_hook_template: ''
# letsencrypt configuration email
letsencrypt_email: ''
# letsencrypt renewal systemd timer
# see: https://www.freedesktop.org/software/systemd/man/systemd.time.html
letsencrypt_renew_timer: '*-*-* 00,12:00:00'
