---

php_version: 7.3

# Apache httpd packages to install
httpd_packages:
  - 'apache2'
  - "php{{ php_version }}"
  - "libapache2-mod-php{{ php_version }}"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-gd"
  - 'php-pear'
  - "php{{ php_version }}-imagick"
# - php7.3-mcrypt
  - "php{{ php_version }}-dev"
  - 'libpcre3-dev'
  - 'libapache2-mod-authnz-external'
  - 'pwauth'

# Enable apache modules
httpd_modules:
  - 'auth_basic'
  - 'authnz_external'
  - 'mpm_prefork'
  - 'autoindex'
  - "php{{ php_version }}"
  - 'include'
  - 'ssl'
  - 'rewrite'
