---

# Apache httpd packages to install
httpd_packages:
  - apache2
  - php7.3
  - libapache2-mod-php7.3
  - php7.3-curl
  - php7.3-gd
  - php-pear
  - php7.3-imagick
# - php7.3-mcrypt
  - php7.3-dev
  - libpcre3-dev
  - libapache2-mod-authnz-external
  - pwauth

# Enable apache modules
httpd_modules:
  - auth_basic
  - authnz_external
  - mpm_prefork
  - autoindex
  - php7.3
  - include
  - ssl
