---

- hosts: debian
  gather_facts: Yes
  remote_user: root

  tasks:
    - name: import home server role
      import_role:
        name: home_server
      tags:
        - hms
    - name: import firewall role
      import_role: 
        name: iptables
      tags:
        - frwl
    - name: import samba role
      import_role:
        name: samba
      tags:
        - smb
    - name: import ftp role
      import_role:
        name: proftpd
      tags:
        - ftp
    - name: import certbot role
      import_role:
        name: certbot
      tags:
        - crt
    - name: import httpd role
      import_role:
        name: apache
      tags:
        - http
