---

- hosts: debian
  gather_facts: Yes
  remote_user: root

  tasks:
    - name: include os tasks
      include: os.yaml
      tags:
        - os
    - name: include users tasks
      include: users.yaml
      tags:
        - users
    - name: include directories tasks
      include: directories.yaml
      tags:
        - os
        - dir
    - name: include samba tasks
      include: samba.yaml
      tags:
        - samba
    - name: include ftp tasks
      include: ftp.yaml
      tags:
        - ftp
    - name: include httpd tasks
      include: httpd.yaml
      tags:
        - http

  handlers:
    - name: restart samba
      service:
        name: smbd
        state: restarted
    - name: restart httpd
      service:
        name: apache2
        state: restarted
    - name: restart ftp
      service:
        name: proftpd
        state: restarted
    - name: restart sshd
      service:
        name: sshd
        state: reloaded
