---

base_path: '/home/srv'

users_dir: 'users'
html_dir: 'www'
cgi_dir: 'cgi-bin'
ftp_dir: 'files'

base_packages:
  - net-tools
  - apt-transport-https
  - python-pip
  - rssh
  - iptables-persistent
  - netfilter-persistent

firewall:
  file: '/etc/iptables/rules.v4'
  minimize_delay:
    - 21
    - 80
    - 443
  opened_tcp_ports:
    - 22
    - 21
    - 80
    - 443
  opened_udp_ports:
    - 137:138
  closed_tcp_ports: []
  closed_udp_ports: []