---

# spaces base path
base_path: '/home/srv'

# space users dir
users_dir: 'users'
# http server files dir for a space
html_dir: 'www'
# http server cgi dir for a space
cgi_dir: 'cgi-bin'
# ftp and samba files dir for a space
ftp_dir: 'files'

# OS base packages to install
base_packages:
  - net-tools
  - apt-transport-https
  - python-pip
  - rssh
  - iptables-persistent
  - netfilter-persistent

# Iptable configuration
# file: rule file name
# minimize_delay: list of ports to minimize delay in mangle table
# opened_tcp_ports: list of tcp ports to open (default all is closed)
#   syntax for a single port (ftp):
#      - '21'
#   syntax for a port range:
#      - '8080:8085'
# opened_udp_ports: list of udp ports to open (default all is closed)
#   syntax for a single port (ftp):
#      - '21'
#   syntax for a port range:
#      - '137:138'
firewall:
  file: '/etc/iptables/rules.v4'
  minimize_delay:
    - 21
    - 80
    - 443
  opened_tcp_ports:
    - 22
    - 21
    - 80
    - 443
  opened_udp_ports:
    - 137:138
  closed_tcp_ports: []
  closed_udp_ports: []