---

# Spaces configuration, and access rights
# primary: default space, do not delete, but configure it as you need.
# <space name>: space name
#   short_name: if your space name is too long (user space name creation will throw an error), set a short name value.
#   user: user master of this space (see file_sharing)
#   group: group allowed to use this space (see file_sharing)
#   comment: explanation of the space
#   services: list of services enabled for this space. Values: [http, samba, ftp]
#   file_sharing: Autheticated access for file sharing or FTP (samba, ftp):
#      - write_user_read_group: Write=user, Read=Group
#      - write_group_read_all: Write=Group, Read=All
#      - write_group_read_group: Write=Group, Read=Group
#   web_access: Public acces for web or Anonymous FTP (http, ftp)
#      - all_internet_no_password: All Internet with no password required, local network with no password required
#      - all_internet_with_password: All internet with password required, local network with password required
#      - all_internet_with_password_except_local: All internet (password required outside local network)
#      - lan_no_password: Local network only with no password required)
#      - lan_with_password: Local network only with password required
#      - no_access: No web (http or ftp) access
#   exec_dynamic: Dynamic content execution (CGI, PHP, SSI)
#      - disable: dynamic content execution disabled
#      - enable: dynamic content execution enabled
#
# Http specific configurations:
#   server_name: virtualhost server name
#   server_alias: virtualhost alias names
#   server_cert_base_path: enable ssl by specify letsencrypt certificate dir path.
#     By default, set it to: "{{ letsencrypt_cert_path }}/{{ letsencrypt_root_cn }}"
#     Ex: server_cert_base_path: "{{ letsencrypt_cert_path }}/{{ letsencrypt_root_cn }}"
spaces:
  primary:
    user: "{{ apache_user }}"
    group: "{{ apache_group }}"
    comment: 'primary'
    services:
      - http
    file_sharing: 'write_user_read_group'
    web_access: 'no_access'
    exec_dynamic: 'disable'
    server_name: 'myserver.local'
    server_alias: 'ftp.myserver.local www.myserver.local'
    state: present
  write_user_read_group_noaccess_disable_b:
    short_name: wu_rg_na_b_b
    user: muzo
    group: muzo_g
    comment: 'write_user_read_group_noaccess_disable'
    services:
      - http
      - samba
      - ftp
    file_sharing: 'write_user_read_group'
    web_access: 'no_access'
    exec_dynamic: 'disable'
    state: present
  write_group_read_all_noaccess_disable_b:
    short_name: wg_ra_na_d_b
    user: muzo
    group: muzo_g
    comment: 'write_group_read_all_noaccess_disable'
    services:
      - http
      - samba
      - ftp
    file_sharing: 'write_group_read_all'
    web_access: 'no_access'
    exec_dynamic: 'disable'
    state: present
  write_group_read_group_noaccess_disable_b:
    short_name: wg_rg_na_d_b
    user: muzo
    group: muzo_g
    comment: 'write_group_read_group_noaccess_disable'
    services:
      - http
      - samba
      - ftp
    file_sharing: 'write_group_read_group'
    web_access: 'no_access'
    exec_dynamic: 'disable'
    state: present
  write_user_read_group_all_internet_no_password_disable_b:
    short_name: wu_rg_ainp_d_b
    user: muzo
    group: muzo_g
    comment: 'write_user_read_group_all_internet_no_password_disable'
    services:
      - http
      - samba
      - ftp
    file_sharing: 'write_user_read_group'
    web_access: 'all_internet_no_password'
    exec_dynamic: 'disable'
    state: present
  write_user_read_group_all_internet_with_password_disable_b:
    short_name: wu_rg_aiwp_d_b
    user: muzo
    group: muzo_g
    comment: 'write_user_read_group_all_internet_with_password_disable'
    services:
      - http
      - samba
      - ftp
    file_sharing: 'write_user_read_group'
    web_access: 'all_internet_with_password'
    exec_dynamic: 'disable'
    state: present
  write_user_read_group_all_internet_with_password_except_local_disable_b:
    short_name: wu_rb_aiwpel_d_b
    user: muzo
    group: muzo_g
    comment: 'write_user_read_group_all_internet_with_password_except_local_disable'
    services:
      - http
      - samba
      - ftp
    file_sharing: 'write_user_read_group'
    web_access: 'all_internet_with_password_except_local'
    exec_dynamic: 'disable'
    state: present
  write_user_read_group_lan_no_password_disable_b:
    short_name: wu_rg_lnp_d_b
    user: muzo
    group: muzo_g
    comment: 'write_user_read_group_lan_no_password_disable'
    services:
      - http
      - samba
      - ftp
    file_sharing: 'write_user_read_group'
    web_access: 'lan_no_password'
    exec_dynamic: 'disable'
    state: present
  write_user_read_group_lan_with_password_disable_b:
    short_name: wu_rg_lwp_d_b
    services:
      - http
      - samba
      - ftp
    user: muzo
    group: muzo_g
    comment: 'write_user_read_group_lan_with_password_disable'
    file_sharing: 'write_user_read_group'
    web_access: 'lan_with_password'
    exec_dynamic: 'disable'
    state: present
  write_user_read_group_lan_no_password_enable_b:
    short_name: ur_rg_lnp_e_b
    services:
      - http
      - samba
      - ftp
    user: muzo
    group: muzo_g
    comment: 'write_user_read_group_lan_no_password_enable'
    file_sharing: 'write_user_read_group'
    web_access: 'lan_no_password'
    exec_dynamic: 'enable'
    state: present
  ftp_only_b:
    services:
      - ftp
    user: muzo
    group: muzo_g
    comment: 'only_ftp_bay'
    file_sharing: 'write_user_read_group'
    web_access: 'lan_with_password'
    exec_dynamic: 'disable'
    state: present
  samba_only_b:
    services:
      - samba
    user: muzo
    group: muzo_g
    comment: 'only_samba_bay'
    file_sharing: 'write_user_read_group'
    web_access: 'no_access'
    exec_dynamic: 'disable'
    state: present
  http_only_b:
    services:
      - http
    user: muzo
    group: muzo_g
    comment: 'only_http_bay'
    file_sharing: 'write_user_read_group'
    web_access: 'lan_with_password'
    exec_dynamic: 'disable'
    server_name: 'www.pouet.com'
    server_cert_base_path: "{{ letsencrypt_cert_path }}/{{ letsencrypt_root_cn }}"
    state: present
  group_hannoerth_write_user_read_group_lan_no_password_disable_b:
    short_name: gh_wu_rg_lnp_d_b
    user: muzo
    group: poto_g
    comment: 'group_hannoerth_write_user_read_group_lan_no_password_disable_b'
    services:
      - http
      - samba
      - ftp
    file_sharing: 'write_user_read_group'
    web_access: 'lan_no_password'
    exec_dynamic: 'disable'
    state: present

  test:
    user: toto
    group: toto_g
    comment: 'test'
    services:
      - http
      - samba
      - ftp
    file_sharing: 'write_user_read_group'
    web_access: 'lan_no_password'
    exec_dynamic: 'disable'
    state: absent
