---

server_users:
  admin:
    groups:
      - 'admin_g'
      - 'muzo_g'
      - 'poto_g'
      - 'saufy_g'
    shell: '/usr/bin/bash'
  muzo:
    groups:
      - 'muzo_g'
      - 'poto_g'
      - 'saufy_g'
  hannoerth:
    groups:
      - 'poto_g'
    ftp_chroot: '/group_hannoerth_write_user_read_group_lan_no_password_disable_b/files'
  saufy:
    groups:
      - 'saufy_g'
