---

# Spaces configuration, and access rights
# primary: default space, do not delete, but configure it as you need.
# <space name>: space name
#   short_name: if your space name is too long (user space name creation will throw an error), set a short name value.
#   user: user master of this space (see file_sharing)
#   group: group allowed to use this space (see file_sharing)
#   comment: explanation of the space
#   services: list of services enabled for this space. Values:
#      - http: enable apache for this space
#      - samba: enable windows file sharing for this space
#      - ftp: enable ftp file sharing for this space
#   file_sharing: Authenticated access for file sharing or FTP [apply to samba, ftp]:
#      - write_user_read_group: Write=User, Read=Group
#      - write_group_read_all: Write=Group, Read=All
#      - write_group_read_group: Write=Group, Read=Group
#   web_access: Public acces for web or Anonymous FTP [apply to http, ftp]
#      - all_internet_no_password: All Internet with no password required, local network with no password required
#      - all_internet_with_password: All internet with password required, local network with password required
#      - all_internet_with_password_except_local: All internet (password required outside local network)
#      - lan_no_password: Local network only with no password required)
#      - lan_with_password: Local network only with password required
#      - no_access: No web (http or ftp) access
#   exec_dynamic: Dynamic content execution (CGI, PHP, SSI) [apply to http]
#      - disable: dynamic content execution disabled
#      - enable: dynamic content execution enabled
#
# Http specific configurations:
#   server_name: virtualhost server name [apply to http]
#   server_alias: virtualhost alias names [apply to http]
#   server_cert_base_path: enable ssl by specify letsencrypt certificate dir path [apply to http].
#     By default, set it to: "{{ letsencrypt_cert_path }}/{{ letsencrypt_root_cn }}"
#     Ex: server_cert_base_path: "{{ letsencrypt_cert_path }}/{{ letsencrypt_root_cn }}"
spaces:
  primary:
    user: "{{ apache_user }}"
    group: "{{ apache_group }}"
    comment: 'primary'
    services:
      - http
    file_sharing: 'write_user_read_group'
    web_access: 'no_access'
    exec_dynamic: 'disable'
    server_name: 'myserver.local'
    server_alias: 'ftp.myserver.local www.myserver.local'
    state: present
  ftp_only:
    user: laurent
    group: ftp_g
    comment: 'FTP only space with password required'
    services:
      - ftp
    file_sharing: 'write_user_read_group'
    web_access: 'all_internet_with_password'
    exec_dynamic: 'disable'
    state: present
  http_only:
    user: laurent
    group: http_g
    comment: 'HTTP only space for my static web site'
    services:
      - http
    file_sharing: 'write_user_read_group'
    web_access: 'all_internet_no_password'
    exec_dynamic: 'disable'
    state: present
  php_only:
    user: laurent
    group: http_g
    comment: 'PHP only space for my dunamic web site'
    services:
      - http
    file_sharing: 'write_user_read_group'
    web_access: 'all_internet_no_password'
    exec_dynamic: 'enabled'
    state: present
  windows_share_only:
    user: laurent
    group: samba_g
    comment: 'Windows share only space'
    services:
      - samba
    file_sharing: 'write_user_read_group'
    web_access: 'no_access'
    exec_dynamic: 'disable'
    state: present
  http_only_with_password_required:
    short_name: http_only_wpr
    user: laurent
    group: http_g
    comment: 'HTTP space protected by password'
    services:
      - http
    file_sharing: 'write_user_read_group'
    web_access: 'all_internet_with_password'
    exec_dynamic: 'disable'
    state: present
  all_in_one:
    user: laurent
    group: friends_g
    comment: 'My all in one space shared with friends'
    services:
      - http
      - ftp
      - samba
    file_sharing: 'write_user_read_group'
    web_access: 'all_internet_with_password'
    exec_dynamic: 'disable'
    state: present
