---

- name: OS| Install base packages
  apt:
    name: "{{ base_packages | join(',') }}"
    state: present

- name: OS| Install python passlib
  pip:
    name: passlib

- name: OS| configure sshd
  template:
    src: 'sshd_config'
    dest: '/etc/ssh/sshd_config'
    mode: 0644
    owner: root
    group: root
  notify: restart sshd

- name: OS| Create base directory
  file:
    path: "{{ base_path }}"
    state: directory
    mode: 0775
    owner: root
    group: root

- name: OS| Get hostname
  command: "hostname"
  register: hostname
  failed_when: "hostname.rc > 0"

- name: OS| Set hostname {{ server_hostname }}
  command: "hostnamectl set-hostname {{ server_hostname }}"
  register: hostnamectl
  changed_when: "hostnamectl.rc == 0"
  failed_when: "hostnamectl.rc > 0"
  when: "server_hostname != hostname.stdout"
