---

- name: Users| Compute server_groups_present & server_primary_groups_absent
  set_fact:
    server_groups_present: "{{ server_users | dict2items | json_query(select_groups_present) | flatten | unique + [ proftpd_shared_group ] }}"
    server_primary_groups_absent: "{{ server_users | dict2items | json_query(select_groups_absent) | flatten | unique }}"
  vars:
    select_groups_present: "[?value.state == 'present'].[key, value.groups]"
    select_groups_absent: "[?value.state == 'absent'].[key]"

- debug:
    var: server_groups_present

- debug:
    var: server_primary_groups_absent

- name: Users| Create groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ server_groups_present }}"

- name: Directories| Create users dir
  file:
    path: "{{ base_path }}/{{ users_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Users| Compute users and passwords
  set_fact:
    server_users_psswds: "{{ server_users | combine(server_passwords, recursive=True)}}"

- name: Users| Create or delete users home dir
  file:
    path: "{{ base_path }}/{{ users_dir }}/{{ item.key }}/home"
    state: "{% if 'absent' == item.value.state %}absent{% else %}directory{% endif %}"
  loop: "{{ lookup('dict', server_users) }}"

- name: Users| Create or delete users
  user:
    name: "{{ item.key }}"
    group: "{{ item.key }}"
    groups: "{% if item.value.groups is defined %}{{ item.value.groups | join(',') + ',' + proftpd_shared_group }}{% else %}{{ proftpd_shared_group }}{%endif%}"
    shell: "{% if item.value.shell is defined %}{{ item.value.shell }}{% else %}/bin/rbash{%endif%}"
    password: "{{ item.value.password | password_hash('sha512', secret_salt) }}"
    home: "{{ base_path }}/{{ users_dir }}/{{ item.key }}/home"
    create_home: no
    state: "{{ item.value.state }}"
    append: no
  loop: "{{ lookup('dict', server_users_psswds ) }}"

- name: Users| Delete users primary groups
  group:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ server_primary_groups_absent }}"

- name: Users| Set users home dir owners
  file:
    path: "{{ base_path }}/{{ users_dir }}/{{ item.key }}"
    state: 'directory'
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    recurse: yes
    mode: 0700
  loop: "{{ lookup('dict', server_users) }}"
  when: "'present' == item.value.state"

- name: Users| Update Apache Httpd user
  user:
    name: "{{ apache_user }}"
    group: "{{ apache_group }}"
    groups: "{{ server_groups_present | join(',') }}"
    append: yes
    state: present

- name: Users| Create spaces technical primary groups
  group:
    name: "{%if item.value.short_name is defined %}{{ item.value.short_name }}{%else%}{{ item.key }}{%endif%}"
    state: present
  loop: "{{ lookup('dict', spaces) }}"
  when: "'present' == item.value.state"

- name: Users| Create or delete spaces technical users
  user:
    name: "{%if item.value.short_name is defined %}{{ item.value.short_name }}{%else%}{{ item.key }}{%endif%}"
    group: "{%if item.value.short_name is defined %}{{ item.value.short_name }}{%else%}{{ item.key }}{%endif%}"
    groups: "{{ proftpd_shared_group }}"
    comment: "{% if item.value.comment is defined %}{{ item.value.comment }}{% else %}{%endif%}"
    shell: "/bin/false"
    home: "{{ base_path }}/{{ item.key }}"
    create_home: no
    password_lock: yes
    state: "{{ item.value.state }}"
  loop: "{{ lookup('dict', spaces) }}"

- name: Users| Delete spaces technical primary groups
  group:
    name: "{%if item.value.short_name is defined %}{{ item.value.short_name }}{%else%}{{ item.key }}{%endif%}"
    state: absent
  loop: "{{ lookup('dict', spaces) }}"
  when: "'absent' == item.value.state"
