---

- name: Firewall| Install pckages
  apt:
    name: "{{ iptables_packages | join(',') }}"
    state: present

- name: Firewall| Create iptables file
  template:
    src: 'iptables.j2'
    dest: "{{ firewall.file }}"
  register: iptables_tpl
  notify: restart iptables

- name: Firewall| Validate iptables configuration
  shell: "iptables-restore -v --test < {{ firewall.file }}"
  register: iptables_rest
  changed_when: "iptables_rest.rc == 0"
  failed_when: "iptables_rest.rc > 0"
  when: "iptables_tpl.changed == true"