---

# Unattended Upgrades documentation:
# https://wiki.debian.org/UnattendedUpgrades

- name: Upgrades| Install unattended upgrades packages
  apt:
    name: "{{ uau_packages | join(',') }}"
    state: present

- name: Upgrades| Enable automatique upgrades
  become: yes
  copy:
    src: "{{ uau_update_file_source }}"
    dest: "{{ uau_update_file_target }}"

- name: Upgrades| Configure automatique upgrades periodically
  become: yes
  copy:
    src: "{{ uau_periodic_file_source }}"
    dest: "{{ uau_periodic_file_target }}"

- name: Upgrades| Configure upgrades
  become: yes
  template:
    src: "{{ uau_configuration_file_source }}"
    dest: "{{ uau_configuration_file_target }}"

- name: Upgrades| Check configuration
  become: yes
  command: unattended-upgrade -d

- name: Upgrades| Create daily download dir
  become: yes
  file:
    state: directory
    path: "{{ uau_daily_download_timer_dir_target }}"

- name: Upgrades| Configure daily download timer
  become: yes
  template:
    src: "{{ uau_daily_download_timer_file_source }}"
    dest: "{{ uau_daily_download_timer_file_target }}"
  notify: restart apt-daily.timer

- name: Upgrades| Create upgrades download dir
  become: yes
  file:
    state: directory
    path: "{{ uau_daily_upgrades_timer_dir_target }}"

- name: Upgrades| Configure upgrades download timer
  become: yes
  template:
    src: "{{ uau_daily_upgrades_timer_file_source }}"
    dest: "{{ uau_daily_upgrades_timer_file_target }}"
  notify: restart service apt-daily-upgrade.timer
