---

- name: restart postfix
  command: postfix reload
  register: postfix
  changed_when: "postfix.rc == 0"
  failed_when: "postfix.rc > 0"

- name: restart dovecot
  service:
    name: dovecot
    state: restarted
