---

# spaces base path
base_path: '/home/srv'

# space users dir
users_dir: 'users'
# http server files dir for a space
html_dir: 'www'
# http server cgi dir for a space
cgi_dir: 'cgi-bin'
# ftp and samba files dir for a space
ftp_dir: 'files'

# OS base packages to install
base_packages:
  - net-tools
  - apt-transport-https
  - python3-pip
